/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeLayoutImport } from './routes/_home/_layout'

// Create Virtual Routes

const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const HomeLayoutIndexLazyImport = createFileRoute('/_home/_layout/')()

// Create/Update Routes

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_home/_layout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexLazyRoute = HomeLayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any).lazy(() =>
  import('./routes/_home/_layout/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home/_layout': {
      id: '/_home/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_home/_layout/': {
      id: '/_home/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutIndexLazyImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  HomeLayoutRoute: HomeLayoutRoute.addChildren({ HomeLayoutIndexLazyRoute }),
  DashboardIndexLazyRoute,
})

/* prettier-ignore-end */
